### ISSUE TITLE
best approach to get remaining time for each device

### ISSUE THREAD

**Issue by gb160** [EvanPurkhiser/prolink-nowplaying-txt#1]
Hi mate, first off many thanks for this...im successfully using it to log the track artist and title info during mixes to generate a cue file for splitting the audio recording file of my mixes and its working spectacularly well, this functionality is only normally available to owners of CDJ-3000 with a V10 mixer (and im not that rich haha)

Anyway onto my main question, I'm using XDJ-1000s (mk2) and one functionality they're missing is a warning LED when a track is coming close to ending, there is a small indicator that comes up on the LCD but its not very prominent and very easy to miss.

So what id like to do is periodically check on the progress of each device and report back if its less than x seconds (so check maybe every 5 - 10 seconds)...I've checked and the information I need to calculate the tracks remaining time all seems to be available with this library (BPM, Slider Pitch, Duration, current beat), but just wondering if you could suggest a suitable approach to periodically getting this data.

Im not too well versed with JS/Typescript...python is my home turf, but this is the only library I've found which is relatively simple to use and most importantly very reliable. 

Again, many thanks for your work on this great project.

**Comment by evanpurkhiser** [comment]
So you won't be able to get the _exact_ remaining time, since the CDJs only send per beat packets (It would be possible to interpolate exact times between beats if you really needed to, which is what [beat-link](https://github.com/Deep-Symmetry/beat-link) does). So you'll only know the exact time at each beat that happens, which in your case should be good enough!

You don't need to poll on anything, you will just want to setup a listener that computes the current time of the track and compares it against the total time.

Here's what that might look like (I didn't test it, so can't be sure it's right!)

```ts
  network.statusEmitter?.on('status', async state => {
    const {trackId, trackSlot, trackType, trackDeviceId} = state;

    // You might want to cache this part so you don't have to 
    // asynchronously look it on each beat.
    const track = await network.db?.getMetadata({
      deviceId: trackDeviceId,
      trackId,
      trackType,
      trackSlot,
    });

    if (!track) {
      return;
    }

    const totalBeats = track.duration / (track.tempo / 60);
    const currentBeat = state.beat ?? 0;

    if (totalBeats - currentBeat < 32) {
      console.log(`Less than 2 PHRASES REMAIN on player ID ${state.deviceId}!!`);
    }
  });
```

If you need the actual remaining time you'll have to do some computations with the pitch slider value. But I think that code should be close to what you're looking for!

--

PS

> this functionality is only normally available to owners of CDJ-3000 with a V10 mixer

Do you have a link that explains that, I didn't know Pioneer had that functionality built into any of their equipment!

**Comment by gb160** [comment]
Thanks for your assistance , this is exactly what im looking for...I should get some time later this week to get it into action.

Regarding the track/artist data, I first noticed this when I was messing around with a buddys DDJ-400, if you record with Rekordbox a .cue file is generated alongside the .wav recording with all the track/artist info populated where it needs to be.

To cut a long story short, I think the feature is only available on other pioneer equipment (CDJ3000 + DJM-V10 mixer) when using the DJM-Rec app from pioneer on a mobile device...its mentioned on this page (the section under Auto Time Stamp):
https://www.pioneerdj.com/en-gb/product/software/djm-rec/dj-app/overview/

Im currently using this app for all my recordings now as I had an old iPhone laying around so I don't have to keep moving my MacBook around to make recordings. 

The iPhone is jailbroken meaning I can get all the track timestamps from the DJM-REC app (the app creates a .plist file in the app's Documents folder) and then combined with the track/artist info from prolink-nowplaying a .cue file is created for all my mixes...Its a long winded way to add a pretty basic feature but its working surprisingly well !

**Comment by evanpurkhiser** [comment]
I'm looking to add cue file creation to [prolink-tools](https://github.com/evanpurkhiser/prolink-tools) in the future as well :)

**Comment by gb160** [comment]
That's excellent news !

I'll close this issue, thanks again.

**Comment by gb160** [comment]
Im back !
Works perfectly 
the only error in your code was:
``` 
const totalBeats = track.duration / (track.tempo / 60);
```
should be:
``` 
const totalBeats = track.duration * (track.tempo / 60);
```

Only slight issue is I get this warning when starting up:
```Bringing up prolink network
Network online, preparing to connect
Autoconfiguring network.. waiting for devices
New device: XDJ-1000MK2 [id: 2]
Autoconfigure successfull!
Connecting to network!
Network connected! Network services initalized
New device: XDJ-1000MK2 [id: 1]
(node:4833) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 connected listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
```

Is this something I should worry about? or should I just set more listeners to silence the warning?

**Comment by evanpurkhiser** [comment]
Hmm. can you run it with `node --trace-warnings` like it mentions?

**Comment by gb160** [comment]
Im out of town for a couple of days mate, I shall try this upon my return and report back. 
Not sure if relevant but I'm running this on a Pi Zero 2 W, which only has 512 MB ram.

**Comment by evanpurkhiser** [comment]
It shouldn't matter, 512mb is way more than enough.

Let's see what the trace warnings says when you come back, no rush!

**Comment by gb160** [comment]
Hi mate, here's the console output with trace warnings:

```
…  awaiting  Bringing up prolink network
✔  success   Network online, preparing to connect
…  awaiting  Autoconfiguring network.. waiting for devices
★  star      New device: XDJ-1000MK2 [id: 1]
…  awaiting  Autoconfigure successfull!
…  awaiting  Connecting to network!
★  star      Network connected! Network services initalized
★  star      New device: XDJ-1000MK2 [id: 2]
(node:1390) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 connected listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:440:17)
    at EventEmitter.addListener (node:events:456:10)
    at /home/pi/node_modules/prolink-connect/lib/index.js:3492:18
    at new Promise (<anonymous>)
    at DeviceManager.getDeviceEnsured (/home/pi/node_modules/prolink-connect/lib/index.js:3490:31)
    at Database.getMetadata (/home/pi/node_modules/prolink-connect/lib/index.js:3244:89)
    at EventEmitter.<anonymous> (file:///home/pi/prolink2/prolink2.mjs:69:41)
    at EventEmitter.emit (node:events:365:28)
    at EventEmitter.emit (node:domain:470:12)
    at Socket.<anonymous> (/home/pi/node_modules/prolink-connect/lib/index.js:7529:82)

```

**Comment by evanpurkhiser** [comment]
Sorry realized I never got back to you on this. I probably wouldn't worry about it unless you run into issues or it bothers you and want to dig further. Let me know and we can re-open the issue!
